version: '3.8'

# Default configuration for development
services:
  socket-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - PORT=4000
      - ORIGIN_URL=${ORIGIN_URL:-http://localhost:3000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Optional: uncomment to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #     reservations:
    #       memory: 128M 